name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dagger
      uses: dagger/dagger-for-github@v3
      with:
        cmds: do test
